### PR TITLE
Symfony 5 support

### PR DESCRIPTION
**Pull request by edgarsn**
Since symfony 5 is released for 3 months now (since November 2019), package should support it as well.

### CODE REVIEW

**Comment by edgarsn** [comment]
Sorry about pushing gitignore from previous pull request. Checked out wrong branch initially. I reverted this file to master so it doesn't conflict with 2nd pull-request.

**Comment by liepumartins** [comment]
@Swedbank-SPP please merge!

**Comment by EdvinasBilius** [comment]
Please merge, your clients are waiting for this!

**Comment by tadaszelvys** [comment]
@Swedbank-SPP please be more active, this pull request is a blocker, please merge.

**Review by Swedbank-SPP — APPROVED** [review]

**Pull request merged**
